/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "stm32f407xx.h"
#include "stm32f407xx_gpio.h"
void delay(void)
{
	for(uint32_t i =0;i<500000;i++);
}
int main(void)
{
	GPIO_Handle_t GPIO_Button;
	GPIO_Button.pGPIOx = GPIOA;
	GPIO_Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GPIO_Button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
	GPIO_Button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_Handle_t GPIO_led;
	GPIO_led.pGPIOx = GPIOD;
	GPIO_led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIO_led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_led.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_led.GPIO_PinConfig.GPIO_PinPupdControl = GPIO_NO_PUPD;
	GPIO_PerClockControl(GPIOD, ENABLE);
	GPIO_PerClockControl(GPIOA, ENABLE);
	GPIO_Inti(&GPIO_Button);
	GPIO_Inti(&GPIO_led);

	for(;;)
	{
		if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0)==1)
		{
			while(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0)==1);
			GPIO_ToggleOutPutPin(GPIOD, GPIO_PIN_NO_12);
		}

	}
}
